# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test CI/CD

on:
  push:
    branches: ['118-create-test-for-get-users']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      tDB_HOST: ohio-postgres.render.com
      tDB_DATABASE: immi
      tDB_USER: immi_user
      tDB_PASSWORD: 728u0NaBqjkKDthf1Kf3BamuFHPnCMdM
      tDB_PORT: 5432
      DB_DROPSCHEMA: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: |
          npm ci
          npm run build --if-present
          npm test
